name: hypergraphcdr
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1
  - blas=1.0
  - brotli-python=1.2.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2025.07.22
  - lcms2=2.16
  - lerc=3.0
  - libabseil=20250127.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.5
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libtheora=1.2.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.4.2
  - opencl-headers=2025.07.22
  - openjpeg=2.5.2
  - openssl=3.0.18
  - opentelemetry-api=1.38.0
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.3
  - pixman=0.46.4
  - pycparser=2.23
  - python=3.10.19
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=72.1.0
  - sleef=3.5.1
  - sqlite=3.51.0
  - tbb=2021.8.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - joblib==1.4.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - multidict==6.1.0
      - numpy==1.26.4
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - propcache==0.2.0
      - psutil==7.1.3
      - pubchempy==1.0.4
      - pyg-lib==0.4.0+pt24cu121
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit==2025.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.5.1+cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-spline-conv==1.2.2+pt24cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - tzdata==2025.2
      - xxhash==3.6.0
      - yarl==1.15.2
